services:
  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
      PORT: 3000
      NODE_OPTIONS: --use-system-ca

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      METRICS_API_URL: ${METRICS_API_URL}
      CARBON_API_URL: ${CARBON_API_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      COLLECTION_INTERVAL_MS: ${COLLECTION_INTERVAL_MS}
      EXTERNAL_API_TIMEOUT_MS: ${EXTERNAL_API_TIMEOUT_MS}

      CORS_ORIGIN: ${CORS_ORIGIN}

      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/app
      - /app/node_modules

    healthcheck:
      test:
        [
         "CMD",
         "node",
          "-e",
          "fetch('http://127.0.0.1:3000/health').then(r => { if (!r.ok) process.exit(1) }).catch(() => process.exit(1))"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:5173"

    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      backend:
        condition: service_healthy

    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  postgres_data: